version: '2'
services:
  redis-device:
    image: "redis"
  redis-cloud:
    image: "redis"
  device:
    build: ../iron-iot-device/
    ports:
      - "8081:8081"
    depends_on:
      - redis-device
  cloud:
    build: ../iron-iot-cloud/
    ports:
      - "8080:8080"
    depends_on:
      - redis-cloud
      - device
