version: '2'
services:

    redis-device:
        image: "redis"
    device:
        build: "../iron-iot-device/"
        ports:
            - "8081:8081"
        depends_on:
            - redis-device

    redis-release:
        image: "redis"
    release:
        build: "../iron-iot-release/"
        ports:
            - "8082:8082"
        depends_on:
            - redis-release

    redis-cloud:
        image: "redis"
    cloud:
        build: "../iron-iot-cloud/"
        ports:
            - "8080:8080"
        depends_on:
            - redis-cloud
            - device
            - release
